### ISSUE TITLE
Ability to inject authorization url

### ISSUE THREAD

**Issue by jefersonralmeida** [greew/oauth2-client#2]
Right now the authorization URL is hard coded inside the Azure class, as a protected property.
Would be great to have the ability to inject a custom URL, having the current one as default.

The reason for that is: If you want to use Azure National Clouds, the URL would be a different one. More info [here](https://learn.microsoft.com/en-us/entra/identity-platform/authentication-national-cloud).

I'll send a PR with the fix soon.

**Comment by jefersonralmeida** [comment]
@greew  Could you please generate a new minor version, so the latest changes go live through composer?

**Comment by greew** [comment]
Sure thing - just forgot about it. Thanks for reminding me! :)
